version: '3'
services:
    db:
        build: .
#            context: .
#            dockerfile: Dockerfile
        image: db/sql
        container_name: sqldw
        ports:
            - "1433:1433"
        environment: 
            SA_PASSWORD: "SqlDevOps2017"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Developer